mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^rec/', include('rec.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tag.urls'))
]

rec/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<movie_id>[\w\-]+)/$', views.movierec, name='movie_rec'),
]

tag/urls.py
from django.conf.urls import url
from . import views

app_name = 'tag'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
]

rec/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class MovieRec(models.Model):
    movie_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    rec1 = models.CharField(max_length=200)
    rec2 = models.CharField(max_length=200)
    rec3 = models.CharField(max_length=200)
    rec4 = models.CharField(max_length=200)
    rec5 = models.CharField(max_length=200)
    rec6 = models.CharField(max_length=200)
    rec7 = models.CharField(max_length=200)
    rec8 = models.CharField(max_length=200)
    rec9 = models.CharField(max_length=200)
    rec10 = models.CharField(max_length=200)

    def __str__(self):
        return self.name

tag/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tag/forms.py
from django import forms

class answerForm(forms.Form):
    answer = 1

rec/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import MovieRec

def index(request):
    return HttpResponse("Hello, world. This is the rec app.")

def movierec(request, movie_id):
    # Get the list of recommended movies from the database
    m = MovieRec.objects.get(pk=movie_id)
    rec_list = [m.rec1, m.rec2, m.rec3, m.rec4, m.rec5,
                m.rec6, m.rec7, m.rec8, m.rec9, m.rec10]

    template = loader.get_template('rec/index.html')
    context = {
        'rec_list' : rec_list,
        'name' : m.name,
        'index_url' : 'index.html',
        'about_url' : 'about.html',
    }

    #output  = ','.join(rec_list)
    return HttpResponse(template.render(context, request))

tag/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from read_files import read_files
from make_prediction import make_prediction
from rec.models import MovieRec

import json
import numpy as np

# Create your views here.

def index(request):
    # load the template
    template = loader.get_template('tag/index.html')

    # load tree variables
    [children_left,children_right,feature] = read_files()
    n_nodes = children_left.size
    # convert to JASON format
    json_children_left = json.dumps(children_left.tolist())
    json_children_right = json.dumps(children_right.tolist())
    json_feature = json.dumps(feature.tolist())

    # reading the user inputs
    if (request.POST.get('ans')):
        leaf_node = request.POST.get('ans')
        leaf_node = int(leaf_node)
        # make a prediction
        predicted_movie = make_prediction(leaf_node) #returns an ndarray
        # randomly choose a movie if more than one returned
        if predicted_movie.size > 1:
            movie_list =[np.choice(predicted_movie)]
        else:
            movie_list = predicted_movie.tolist()

        movie_id = str(MovieRec.objects.get(name=movie_list[0]).movie_id)
        json_predicted_movie = json.dumps(movie_list)

    else:
        predicted_movie = ["none"]
        movie_id = None
        json_predicted_movie = json.dumps(predicted_movie)
    

    # create context to pass to the template
    context = {
        'json_children_left':json_children_left,
        'json_children_right':json_children_right,
        'json_feature':json_feature,
        'json_predicted_movie':json_predicted_movie,
        'predicted_movie_py':predicted_movie,
        'movie_id_py':movie_id,
        'n_nodes':n_nodes,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    # load the template
    template = loader.get_template('tag/about.html')

    # create context to pass to the template
    context = {
    }

    return HttpResponse(template.render(context, request))

rec/templates/rec/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Movie Recommendation</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="Movie recommendation">
		<meta name="author" content="NNVUTISA">
		<meta name="robots" content="index, follow">

		<!-- Override CSS file - add your own CSS rules -->
                {% load staticfiles %}
		<link rel="stylesheet" href="{% static "rec/styles.css" %}">
	</head>
	<body>
		<div class="container">
			<div class="header">
				<h1 class="header-heading">MOVIE TAG</h1>
			        <h5 class="header-exp">Not sure what movie to watch?
			        Answer some questions and let me suggests a movie for you.</h5>
			</div>
			<div class="content">
				<div class="left_box">
					<p> Movies similar to <b>{{ name }} </b></p>
				</div>
				<div class="right_box">
					<ul class="list-circle">
						{% for movie in rec_list %}
  							<li>{{ movie }}</li>
  						{% endfor %}
					</ul>  
				</div>
			</div>
				
			<div class="footer">
				<ul class="nav">
				        {% url 'about' as about_url %}
				        {% url 'index' as index_url %}
				        <li><a href="{{ index_url }}">Home</a></li>
					<li><a href="{{ about_url }}">About</a></li>
					<li><a
				href="https://nnvutisa.wordpress.com/2016/06/10/movie-tag-project/">
					Blog</a></li>
				</ul>
			</div>
		</div>

	</body>


</html>

tag/templates/tag/about.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>About</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="Movie recommendation">
		<meta name="author" content="NNVUTISA">
		<meta name="robots" content="index, follow">

		<!-- Override CSS file - add your own CSS rules -->
                {% load staticfiles %}
		<link rel="stylesheet" href="{% static "tag/styles.css" %}">
	</head>
	<body>
		<div class="container">
			<div class="header">
				<h1 class="header-heading">MOVIE TAG</h1>
			        <h5 class="header-exp">Not sure what movie to watch?
			        Answer some questions and let me suggests a movie for you.</h5>
			  
			</div>
			<div class="content">
				<div class="main">
					<center>
				        <div class="about">
					    <p>This project made
				        use of movie tag data from
			                <a href="http://grouplens.org/datasets/movielens/">
				        MovieLens Tag Genome
			                Dataset.</a> The project was inspired by the
			                idea of movie recommendation based on
		 	                sentiments. For
			                those who are interested, you can read more about how this app works on 
			                <a href="https://nnvutisa.github.io/articles/2016-06/build-a-movie-app">my blog</a>
			                or check out the code on the movie recommendation app on 
			                <a href="https://github.com/nnvutisa/movietag">Github</a>.</p>
					</div>
				        </center>
				</div>
			</div>
				
			<div class="footer">
				<ul class="nav">
				        {% url 'tag:about' as about_url %}
				        {% url 'tag:index' as index_url %}
				        <li><a href="{{ index_url }}">Home</a></li>
					<li><a href="{{ about_url }}">About</a></li>
				</ul>
			</div>
		</div>
		<form method="post" action="" id="answer_form">
		        {% csrf_token %}
		        <input type="hidden" name="ans" id="hdd" value="">
		</form>
		
	</body>
</html>

tag/templates/tag/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Movie Tag Quiz</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="Movie recommendation">
		<meta name="author" content="NNVUTISA">
		<meta name="robots" content="index, follow">

		<!-- Override CSS file - add your own CSS rules -->
                {% load staticfiles %}
		<link rel="stylesheet" href="{% static "tag/styles.css" %}">
	</head>
	<body>
		<div class="container">
			<div class="header">
				<h1 class="header-heading">MOVIE TAG</h1>
			        <h5 class="header-exp">Not sure what movie to watch?
			        Answer some questions and let me suggests a movie for you.</h5>
			  
			</div>
			<div class="content">
				<div class="main">
					<h2><center><p id="question"></p></center></h2>
				        <div id="buttons">
					        <center>
					        <button class="btn" onclick="myFunction_yes()">YES</button>
					        <button class="btn" onclick="myFunction_no()">NO</button>
					        </center>
						</div>
					{% if predicted_movie_py.0 != "none" %}
					        <div class="answer">
					        <center>
					                <h4><p>Try this movie:</p></h4>
					                <h2><p id="prediction"></p></h2>
					                <p><a href={{ "/rec/"|add:movie_id_py }}>More movies like this one</a></p>
					        </center>
					        </div>
					{% endif %}
				 </div>
			</div>
				
			<div class="footer">
				<ul class="nav">
				        {% url 'tag:about' as about_url %}
				        {% url 'tag:index' as index_url %}
				        <li><a href="{{ index_url }}">Home</a></li>
					<li><a href="{{ about_url }}">About</a></li>
				</ul>
			</div>
		</div>
		<form method="post" action="" id="answer_form">
		        {% csrf_token %}
		        <input type="hidden" name="ans" id="hdd" value="">
		</form>

	</body>

<script type="text/javascript">
    var i=0;
    var cl = {{ json_children_left|safe }};
    var cr = {{ json_children_right|safe }};
    var feature = {{ json_feature|safe }};
    var predicted_movie = {{ json_predicted_movie|safe }};
    var n_nodes = {{ n_nodes }};
    var current_node = 0;

    var question = "Do you want "+feature[0]+"?";
    document.getElementById("question").innerHTML = question;

    function myFunction_yes() {
        current_node = cr[current_node];
        if (feature[current_node] != "None") {
            question = "Do you want "+feature[current_node]+"?";
            document.getElementById("question").innerHTML = question;
            i=i+1;
        } else {
            document.getElementById("hdd").value = current_node;
            document.getElementById("answer_form").submit();
        }
    }

    function myFunction_no() {
        current_node = cl[current_node];
        if (feature[current_node] != "None") {
            question = "Do you want "+feature[current_node]+"?";
            document.getElementById("question").innerHTML = question;
            i=i+1;
        } else {
            document.getElementById("hdd").value = current_node;
            document.getElementById("answer_form").submit();
        }
    }

    document.getElementById("prediction").innerHTML = predicted_movie;
    document.getElementById("movie_id").innerHTML = movie_id;

<!--document.write(cl);-->
</script>


</html>